version: '3.8'
networks:
   default:
    name: net1
    # external: true
services:
  backend: 
    build: ./
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports: 
      - 3333:3333 
    # links:
    #  - redis:redis  
    networks:
      - default
    depends_on:
      - redis  
    command: sh -c "sleep 10 && npm start"  
  redis:
    image: redis:latest
    container_name: redis1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    # volumes:
    #   - .db:/data
    restart: always
    entrypoint: redis-server --appendonly yes    
    networks:
      - default
    